### ISSUE TITLE
legends/plots overlapping in documentation

### ISSUE THREAD

**Issue by SabrinaRichter** [theislab/squidpy#282]
Hey,

I noticed that plots and legends are overlapping, e.g. here: https://squidpy.readthedocs.io/en/latest/auto_tutorials/tutorial_imc.html

**Comment by giovp** [comment]
thanks for pointing it out. I think this is low priority for now, but definitely to have a look for next release!

**Comment by michalk8** [comment]
Small pitch: I'd redo the plot using barcharts instead of scatterplots - think it will be easier to interpret (esp. reorider the bars in ascending order according to their height). That way, cluster names could be on the x-axis (so no more legend) and  the bars would be colored by the cluster colors.

**Comment by giovp** [comment]
I think this is a very minor bug and I personally am not in favour of bar charts as the original visualization (as well as similar, see #349 ) are with line plots. I would close this
