### ISSUE TITLE
Readme and contributing guides in docs

### ISSUE THREAD

**Issue by hspitzer** [theislab/squidpy#287]
@michalk8 @giovp 
I'm currently preparing the contributing guide for `squidpy_notebooks` and was wondering if / how this is going to appear on the docs? For the main readme (index page) I saw that there is a file in `docs/source/index.rst`. Is this copied from `README.rst`? Or is it linked? Should we copy the `CONTRIBUTING.rst` files from `squidpy` and `squidpy_notebooks` there as well? Or is there a more automatic way to link the files?

Btw, I also noticed that atm the link to `CONTRIBUTING.rst` in the docs is broken, as there is no such file in `docs/source`:  https://squidpy.readthedocs.io/en/latest/

**Comment by michalk8** [comment]
@hspitzer 
I see it, in `docs/source/index.rst`, it points to a non-existent file (should be 2 levels above).
However, if you want to have `Contributing` section on the left panel, such as `Release notes`, etc., the `CONTRIBUTING.rst` will require some minor changes, since the links there are defined to be relative to it's position (like `squidpy/im`, etc.) from the root of the repo. 
As for contributing in `squidpy_notebooks`, I have a general copying mechanism, we can just add that file and copy it during build, that's not a problem.
Here are possible solutions (ordered from least to most effort):
1. just mention the respective contributing guides in each repo by only including links to them
2. create a separate section called `Contributing`, add some short flavor text and do step 1. (i.e. just link the guide files)
3. create a separate section as above, that will directly embed those 2 `CONTRIBUTING.rs` files
4. "ditch" top-level CONTRIBUTING.rst and have 1 only in docs/notebook docs (there, we could easily refer to other functions/modules/tutorials/etc.)

As said above, 3. will require 2 things: download CONTRIBUTING from `squidpy_notebooks` (easy), and modify the links to be absolute (e.g. `https://github.com/theislab/squidpy/im` instead of `squidpy/im`).
For 4, if we were to have \:func:`squidpy.im.ImageContainer\` both in repo and in docs, it would only be correctly displayed in docs.

I don't have any preference, I've let you and @giovp decide.

**Comment by hspitzer** [comment]
Thanks for the detailed answer! I think easiest would be to just link to the contributing files in `squidpy` and `squidpy_notebooks` (so option 1). They are rendered nicely on GitHub as well and its least effort for us :-)
