### ISSUE TITLE
Segmenting a crop expects wrong dimensions

### ISSUE THREAD

**Issue by michalk8** [theislab/squidpy#333]
### Description

In #320, propagating absolute crop coords was fixed (i.e. if a crop had coords `(100, 100, 200, 200)` and another crop was made with coords [rel to previous crop] `(50, 50, 100, 100)`, it would be correctly updated to `(150, 150, 200, 200)`, as absolute coords w.r.t. to the original image).
However, in the tutorial below, a crop is directly passed, gets cropped again (with `size=None` it's the same image) and gets correctly updated with the absolute crop coords. This causes an issue in `uncrop`, because the now absolute positin is `(1000, 1000, 2000, 2000)` instead of the relative crop `(0, 0, 1000, 1000)`, causing it to expect an image of shape `(2000, 2000)` and not of `(1000, 1000)`.
In #324 , we no longer rely on our cropping, so it should be fine.
@hspitzer does it make sense to have relative crop coords w.r.t. to the image we're cropping from, rather then the original uncropped image? It would mean essentially to add an option to not add the old+new coords in https://github.com/theislab/squidpy/blob/master/squidpy/im/_utils.py#L163.
I think the way things are currently should be fine.

### Minimal reproducible example
https://github.com/theislab/squidpy_notebooks/blob/master/examples/image/compute_segment_fluo.py

### Version

master

**Comment by hspitzer** [comment]
right, I had not considered that uncrop will always uncrop to the original image and would thus break segmenting from a cropped image.
I would not add an option to change the chaining behaviour of crop -- I think the crop coords should always refer to the original image to allow relating information from `adata` to `img`. 
As #324 uses dasks `map_overlap`, I don't think we need to change anything. Otherwise I could imagine a solution where uncrop also knows about the initial offset that it should reconstruct images to (if so desired), i.e. enabling us to uncrop to a cropped image. 
Btw, in the tests that I implemented for #320 I actually use that uncrop recreates the original image, even if chaining multiple crops; so if we change something in its behaviour (or decide to remove the function), we will have to change this as well. 

We should just make sure do document this behaviour of uncrop very clearly, so users are not surprised. I can make an example vignette showing how to chain cropping + scaling and how uncrop then works.

**Comment by michalk8** [comment]
>  I would not add an option to change the chaining behaviour of crop -- I think the crop coords should always refer to the original image to allow relating information from adata to img.

Agreed, let's not complicate this.

> We should just make sure do document this behaviour of uncrop very clearly, so users are not surprised. I can make an example vignette showing how to chain cropping + scaling and how uncrop then works.

Good idea, though I'd say this is low prio.

**Comment by michalk8** [comment]
closed via #324
