### ISSUE TITLE
Slide-SeqV2 data 

### ISSUE THREAD

**Issue by bromleyjd** [theislab/squidpy#338]
Hi all, your squidpy platform is awesome! I was wondering if you have any functions that are compatible/able to be implemented for analyzing Slide-SeqV2 data? Do you have any plans to implement slide-seq compatible functions to squidpy in the near future? It's been great using scanpy for single-cell analyses and it would be awesome to have something similar for slide-seq!

**Comment by giovp** [comment]
hi @bromleyjd ,

thanks a lot for the interest in squidpy! We are in the process of preparing a tutorial for the analysis of slideseq data. For now, you can try out basically all the functions in `squindpy.gr` module.

I'd suggest you to take a look at this tutorial on how to import slideseq data in aformat that is compatible with squidpy: https://squidpy.readthedocs.io/en/latest/auto_tutorials/tutorial_read_spatial.html

let me know if there is any specific analysis/task you have in mind!

**Comment by bromleyjd** [comment]
Amazing thanks so much!!

Joshua D. Bromley
PhD Student | Shalek Lab
MIT Microbiology Program
(801)-554-4027


From: Giovanni Palla ***@***.***>
Reply-To: theislab/squidpy ***@***.***>
Date: Wednesday, May 12, 2021 at 9:37 AM
To: theislab/squidpy ***@***.***>
Cc: Joshua David Bromley ***@***.***>, Mention ***@***.***>
Subject: Re: [theislab/squidpy] Slide-SeqV2 data (#338)


hi @bromleyjd<https://github.com/bromleyjd> ,

thanks a lot for the interest in squidpy! We are in the process of preparing a tutorial for the analysis of slideseq data. For now, you can try out basically all the functions in squindpy.gr module.

I'd suggest you to take a look at this tutorial on how to import slideseq data in aformat that is compatible with squidpy: https://squidpy.readthedocs.io/en/latest/auto_tutorials/tutorial_read_spatial.html

let me know if there is any specific analysis/task you have in mind!

**Comment by giovp** [comment]
hi @bromleyjd  ,

we are gonna release squidpy 1.2 sometime next week. Meanwhile, if you install it with pip install -e . from the dev branch, you can already try out the new tutorials.

Here the slideseqv2: https://squidpy.readthedocs.io/en/latest/auto_tutorials/tutorial_slideseqv2.html

If you have your own slideseq data, you can follow this tutorial in order to load your data:
https://squidpy.readthedocs.io/en/latest/auto_tutorials/tutorial_read_spatial.html

let us know if that helps! I'm gonna close the issue for now but feel free to reopen if not resolved.
