### ISSUE TITLE
NaN p-values in ligand-receptor interaction results

### ISSUE THREAD

**Issue by lazappi** [theislab/squidpy#361]
Hi

I have been playing around with the `squidpy.gr.ligrec()` function and noticed you get a lot of `NaN` p-values returned. The code is a bit beyond me but I think this should only happen when interactions are filtered because of the `threshold` value but even after setting `threshold = 0.0` I see some `NaN` p-values when there is a calculated mean greater than zero. Any thoughts about what is going on here?

I also noticed that turning on multiple testing correcting (for example with `corr_method = "fdr_bh"`) results in more `NaN`s. I think that is because of this line:

https://github.com/theislab/squidpy/blob/c0220c907577196db5f0dd18ff572648a1450612/squidpy/gr/_ligrec.py#L152

What is the motivation for this? Seems a bit strange to me but maybe there is a technical reason to not return these values?

**Comment by michalk8** [comment]
> I think this should only happen when interactions are filtered because of the threshold value but even after setting threshold = 0.0

NaN values can happen in 2 cases (should be also in the docs):
- when mean expression of 1 interacting cluster is 0
- or 1 of the interacting components didn't pass the threshold

However, I've noticed a bug which was converting 0s to NaN, so this might also be an issue (+ there was 1 another bug when plotting p-value of 0). Both of them should be fixed in #362, which will be merged into `dev`.

> What is the motivation for this? Seems a bit strange to me but maybe there is a technical reason to not return these values?

You're right, should be `qvals[np.isnan(pvals)] = np.nan`

**Comment by lazappi** [comment]
👍🏻 Thanks for the clarification and bug fixes!

**Comment by michalk8** [comment]
Great! I think this can be closed (feel free to reopen).
closed via #362
