### ISSUE TITLE
Import from scanpy object or local files

### ISSUE THREAD

**Issue by nbartonicek** [theislab/squidpy#407]
Good day, wanted to ask what is the way to import objects from either a scanpy or from local h5 and image files. I want to run tutorials but not sure where to start loading my own data. Probably missing something obvious! :) Thanks!
Nenad

**Comment by giovp** [comment]
hi @nbartonicek , thank for the interest in squidpy. 
If you want to read visium data, you can use `scanpy.read_visium` https://scanpy.readthedocs.io/en/stable/generated/scanpy.read_visium.html and for the large tissue image, use the squidpy image container https://squidpy.readthedocs.io/en/latest/auto_tutorials/tutorial_image_container.html 

if you don't have visium data, you can still import molecular, spatial and image data in anndata + iamge container easily, here's a walkthrough on how to do that: https://squidpy.readthedocs.io/en/latest/auto_tutorials/tutorial_read_spatial.html

let us know if you encounter any problem!

**Comment by nbartonicek** [comment]
Thank you for the prompt reply and all the information!

What solved my problem for small visium "hires" images:
image=adata.uns[spatial_key][library_id]["images"]["hires"]

And for big tiffs:
from PIL import Image
source_image_path="tissue_hires_image.tiff"
Image.MAX_IMAGE_PIXELS=None
im = Image.open(source_image_path)
image = numpy.array(im)

Followed by: 
img = sq.im.ImageContainer(image_hires)

Thanks again! :)

Cheers,

Nenad

**Comment by giovp** [comment]
thanks for your reply. I see that works, but according to this code snippet

> And for big tiffs:
from PIL import Image
source_image_path="tissue_hires_image.tiff"
Image.MAX_IMAGE_PIXELS=None
im = Image.open(source_image_path)
image = numpy.array(im)

> Followed by:
img = sq.im.ImageContainer(image_hires)

you wont be using the big tiff file in the image container (as you are assigning the visium hires, which is way lower resolution that the tiff). Is that whhat you are in interested in doing ?

**Comment by giovp** [comment]
@nbartonicek is the issue solved?

**Comment by giovp** [comment]
@nbartonicek I'll close this, please reopen if you have further questions

**Comment by livyring** [comment]
Hi! I am relatively new to using squidpy as well. I just finished processing my 10X visium data using the scanpy tutorials. I am having the same issue, where I am unsure how to add my 10X highres image from the cell ranger output to the image container. Is it as simple as setting img = (path_to_tissue_highres_image.png)? I dont believe there is a tiff file in the cellranger outs folder I have for my experiment.

Thank you!!!

**Comment by livyring** [comment]
Thank you! When I save the processed 10x visium files, I initially re-imported it for analysis using the sc.read_h5ad(). Is that incorrect? Should I be reading in the saved, processed data using the read.visium function?

For reference, after processing my data I used the adata.write() to save it as a h5ad. Should I be doing something else?

**Comment by giovp** [comment]
no then it's fine, you can read and write h5ad as you like. the reading functions for spatial data are just to read the "raw" files. Sounds good for library_id, it just needs to be a unique id

**Comment by livyring** [comment]
Thanks again. I am still having difficulty creating the image container object from the high res image. I understand that the image is stored in the anndata object in the adata.uns['spatial'][<library_id>] slot. This means that I don't have to load in another dataset/file after loading in the processed H5ad file that I made, correct?  Both the H&E Visium tutorial and the Import spatial data in AnnData and Squidpy tutorials aren't informative on how to make the image container object after processing the 10X data yourself and having 1 processed anndata file from it.

The H&E tutorial has you load in a seperate file for the image to create the image container
The tutorial for loading the anndata writes an original image.

I may just have a fundamental misunderstanding of where this image comes from in order to put it into the image container. I watched your seminar on youtube that came out a week ago where you went over the "import spatial data in AnnData and Squidpy" tutorial (https://www.youtube.com/watch?v=btqPgui8gpg&t=3545s) (which was very helpful and informative in many regards) but it didn't help me with this problem. 

Thanks so much again, sorry I just can't seem to find the way to extract the image from the H5ad processed file and make the image container

**Comment by livyring** [comment]
Yes this is great! thank you!!

**Comment by midichlorianrich** [comment]
Hi,

I am trying the https://squidpy.readthedocs.io/en/stable/auto_tutorials/tutorial_visium_fluo.html tutorial.
But I am having issues assigning the hires figure from my own visium data loaded via the command sq.read.visium() to img = in squidpy.
I could not figure it out using the info above.
Spent hours trying different things.
Unfortunately the tutorial uses this command img = sq.datasets.visium_fluo_image_crop()

thank you!
