### ISSUE TITLE
DLL load failed while importing _arpack: The specified procedure could not be found.

### ISSUE THREAD

**Issue by rachel662** [theislab/squidpy#430]
Hi, 
when importing squidpy I get this error, would anyone be able to help me fix it? 

thanks!
Rachel

**Comment by michalk8** [comment]
Hi @rachel662 ,
could you please post the full error/your os/whether you use conda? Otherwise, it's a bit hard to figure.
Most likely due to broken` numpy`/`scipy`, see [here](https://stackoverflow.com/questions/54083514/how-to-fix-importerror-dll-load-failed-the-specified-procedure-could-not-be-f) for a possible solution.

**Comment by michalk8** [comment]
I am going to assume this has been resolved, if not, feel free to re-open.
